<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Phalcon PHP Framework</title>
    <?php echo $this->assets->outputCss('styleslogin'); ?>    
    <?php echo $this->assets->outputJs('scripts'); ?> 
  </head>
    <body id="page-top" > 
<div class="row">
  <?php echo $this->flashSession->output(); 
 
  $username='';
  $password='';
  $rememberMe='';
 
  if($this->cookies->has("username") && $this->cookies->has("password") )
  {
      $username=$this->cookies->get("username");
      $password=$this->cookies->get("password");
      $rememberMe='checked';
  }
?>
<div class="col-sm">
</div>
<div class="col-sm">
  <form action="" method="post">
  
    <div class="form-group ">
      <label>Email address</label>
      <input type="email" name="email" class="form-control" id="email" placeholder="Enter email" value="<?php if(isset($username))echo $username; ?>" required>
    </div>
    <div class="form-group">
      <label>Password</label>
      <input type="password" name="password" class="form-control" id="password" placeholder="Password" value="<?php if(isset($password))echo $password; ?>" required>
     
    </div>
    <div class="form-check">
      <input type="checkbox" name="rememberMe" class="form-check-input" id="rememberMe" value="1" <?php echo $rememberMe;?>>
 
      <label class="form-check-label" for="rememberMe">Remember me</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
   
    <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
   
  </form>
  </div>
  <div class="col-sm">     
    </div>
  </div>
  </html>