<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>PHP HOMEWORK</title>  
    <?php echo $this->assets->outputCss(''); ?>    
    <?php echo $this->assets->outputJs('scripts'); ?>   
  </head>
  <body>
<div class="container"><?php echo $this->getContent(); ?></div>
 
</body>
</html>
